# Generated by Django 5.2.11 on 2026-02-15 11:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financial_planning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "risk_score",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolios",
                        to="financial_planning.financialplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "portfolios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("STOCK", "Stock"),
                            ("BOND", "Bond"),
                            ("MUTUAL_FUND", "Mutual Fund"),
                            ("ETF", "ETF"),
                            ("REAL_ESTATE", "Real Estate"),
                            ("CRYPTO", "Cryptocurrency"),
                            ("FIXED_DEPOSIT", "Fixed Deposit"),
                            ("OTHER", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("symbol", models.CharField(blank=True, max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("purchase_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="investments.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "holdings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total_return", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "percentage_return",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_history",
                        to="investments.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_performance",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
